name: Deploy to GitHub Pages

on:
  # 监听 push 到 main 分支的操作
  push:
    branches: ["main", "posts"]
  # 允许手动触发部署
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Theme
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Clean Test Posts
        run: rm -rf src/content/posts/*

      - name: Checkout Posts Content
        uses: actions/checkout@v4
        with:
          ref: posts
          path: src/content/posts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        # 使用 --install-links 是为了确保一些依赖能正确安装
        run: npm install

      - name: Build site
        run: npm run build

      - name: Upload artifact
        # 这一步非常重要，手动将打包出来的 dist 文件夹上传给 GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
